### PR TITLE
CommittingChanges: Reword Security update -> Recommended version

### PR DESCRIPTION
**Pull request by mitchdz**
This is my understanding of the versioning scheme. Please reject if this is incorrect.

### CODE REVIEW

**Comment by mitchdz** [comment]
Actually I think this rule might be wrong and instead the updated version string will be a point release. Regardless, I would  like some clarification of SRU rules in this guide.

**Comment by mitchdz** [comment]
Okay I think this is now the general guidance on what to do.

**Comment by mitchdz** [comment]
The table does answer the question, I was just being tripped up by the nomenclature "Security update" and I imagine others might as well. Propose changing to to "Suggested update"

**Comment by panlinux** [comment]
Sorry, I have read it again and I think "Recommended version" is better than "Suggested update"   🙃

Oh, what would the world be like without a bit of bikeshedding, heh?

**Comment by mitchdz** [comment]
No worries, easy change

**Pull request merged**
