### PR TITLE
Remove unnecessary "squash changelog" merge step

### PR DESCRIPTION
**Pull request by basak**
I don't think this step is necessary. Does any reviewer want to stop me and tell me why this needs to be here?

### CODE REVIEW

**Review by utkarsh2102 — CHANGES_REQUESTED** [review]
Why are they being deemed as unnecessary? Afaik, git-ubuntu cannot do this step automatically. We still have to fix the d/ch and rebase and do the mentioned steps. I did that 2 days ago.

**Comment by basak** [comment]
There is no need to squash changelog edits into the automatically generated commits. It doesn't affect the workflow in any way to skip this step, since on the next merge they will just stay as-is in "split" and be dropped from "logical" the same as the automatic changelog commits. It does no harm for there to be an additional "here's how I cleaned up the automatically generated changelog commits" commit. And I doubt anyone is actually reviewing the changelog commits individually; only the final result. So why is it necessary for this step to remain, making the whole process longer to train somebody else up on?

**Review by utkarsh2102 — APPROVED** [review]
After talking about this in person, I think it shouldn't be mandatory and it's a personal choice instead. So I am good with this change.

**Comment by utkarsh2102** [comment]
@basak: there's a conflict. Would you mind fixing that?

**Comment by basak** [comment]
I'll take care of that. Thanks!

**Pull request merged**
